# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-07 03:15
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customer',
            name='date_of_birth',
            field=models.DateTimeField(default=datetime.date.today, verbose_name='date of birth'),
        ),
    ]
